name: Phone home to report status
description: Reports the workflow status to the dispatcher
inputs:
  phone-home-input:
    description: Metadata to phone-home
    type: string
    required: true
  target-url:
    decription: Override the status URL
    type: string
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  context:
    description: Override the context status (not recomended, othewrise the original PR will keep the original context pending for a result)
    type: string
    required: false
  status:
    description: Override the status result (success, failure, pending, ...)
    type: string
    required: false

runs:
  using: node20
  main: main/main.js
  post: post/post.js
